import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
INSTALLER = ROOT / "scripts" / "install_student_os.py"
PLUGIN_ROOT = ROOT / "integrations" / "dsh"
PLUGIN_ENTRY = PLUGIN_ROOT / "dist" / "index.js"
OVERLAY_RELATIVE = Path(".dsh") / "student-os.cordis.yml"
SKILL_RELATIVE = Path(".dsh") / "skills" / "student-os"
MANIFEST_NAME = ".student-os-install.json"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Bootstrap Student OS project-scope support for DeepSeek Harness.")
    parser.add_argument(
        "--project-root",
        required=True,
        help="Target learning vault / current DSH workspace. This is not the college-student-workflow checkout.",
    )
    parser.add_argument("--json", action="store_true", help="Print machine-readable output.")
    return parser.parse_args()


def json_safe_path(path: Path) -> str:
    return str(path.resolve())


def yaml_single_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def overlay_text(plugin_entry: Path) -> str:
    plugin_path = plugin_entry.resolve().as_posix()
    return (
        "# Generated by scripts/bootstrap_dsh.py. Keep this project-local.\n"
        "- insert:\n"
        "    - id: student-os-native\n"
        f"      name: {yaml_single_quote(plugin_path)}\n"
    )


def run_checked(argv: list[str], *, cwd: Path, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        argv,
        cwd=cwd,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
        env={
            **os.environ,
            "PYTHONIOENCODING": "utf-8",
            "PYTHONDONTWRITEBYTECODE": "1",
            **(env or {}),
        },
    )


def fail(stage: str, error: str, **extra: Any) -> dict[str, Any]:
    return {"ok": False, "stage": stage, "error": error, **extra}


def existing_skill(project_root: Path) -> dict[str, Any] | None:
    destination = (project_root / SKILL_RELATIVE).resolve()
    manifest_path = destination / MANIFEST_NAME
    skill_path = destination / "SKILL.md"
    if not destination.exists():
        return None
    if not manifest_path.exists() or not skill_path.exists():
        return None
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if manifest.get("agent") != "dsh" or manifest.get("scope") != "project":
        return None
    if Path(str(manifest.get("target_path", ""))).resolve() != destination:
        return None
    return {
        "installed": True,
        "path": json_safe_path(destination),
        "status": "unchanged",
        "method": str(manifest.get("install_method", "")),
        "manifest": json_safe_path(manifest_path),
    }


def install_skill(project_root: Path) -> dict[str, Any]:
    current = existing_skill(project_root)
    if current is not None:
        return current

    try:
        result = run_checked(
            [
                sys.executable,
                "-B",
                str(INSTALLER),
                "--agent",
                "dsh",
                "--scope",
                "project",
                "--project-root",
                str(project_root),
                "--json",
            ],
            cwd=ROOT,
        )
    except subprocess.CalledProcessError as exc:
        message = (exc.stderr or exc.stdout or str(exc)).strip()
        raise RuntimeError(message) from exc

    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"Installer did not return JSON: {exc}") from exc

    installs = payload.get("results")
    if not isinstance(installs, list) or len(installs) != 1:
        raise RuntimeError("Installer returned an unexpected result shape")
    install = installs[0]
    destination = Path(str(install.get("destination", project_root / SKILL_RELATIVE))).resolve()
    return {
        "installed": True,
        "path": json_safe_path(destination),
        "status": install.get("status", ""),
        "method": install.get("method", ""),
        "manifest": install.get("manifest", ""),
    }


def build_plugin() -> dict[str, Any]:
    if not (PLUGIN_ROOT / "package-lock.json").exists():
        raise RuntimeError("integrations/dsh/package-lock.json is required for npm ci")
    node_exe = shutil.which("node.exe") or shutil.which("node")
    npm_exe = shutil.which("npm.cmd") or shutil.which("npm")
    if node_exe is None:
        raise RuntimeError("Node.js executable was not found on PATH")
    if npm_exe is None:
        raise RuntimeError("npm executable was not found on PATH")

    try:
        run_checked([npm_exe, "ci", "--ignore-scripts", "--no-audit", "--no-fund"], cwd=PLUGIN_ROOT)
        run_checked([npm_exe, "run", "build"], cwd=PLUGIN_ROOT)
    except subprocess.CalledProcessError as exc:
        detail = (exc.stderr or exc.stdout or str(exc)).strip()
        raise RuntimeError(detail) from exc

    if not PLUGIN_ENTRY.exists():
        raise RuntimeError(f"Plugin build did not create {PLUGIN_ENTRY}")
    return {
        "built": True,
        "source": json_safe_path(PLUGIN_ROOT),
        "entry": json_safe_path(PLUGIN_ENTRY),
    }


def write_overlay(project_root: Path) -> dict[str, Any]:
    overlay = (project_root / OVERLAY_RELATIVE).resolve()
    overlay.parent.mkdir(parents=True, exist_ok=True)
    overlay.write_text(overlay_text(PLUGIN_ENTRY), encoding="utf-8")
    return {"written": True, "path": json_safe_path(overlay)}


def bootstrap(project_root: Path) -> tuple[int, dict[str, Any]]:
    project_root = project_root.resolve()
    try:
        project_root.mkdir(parents=True, exist_ok=True)
    except Exception as exc:
        return 1, fail("project-root", str(exc), project_root=json_safe_path(project_root))

    try:
        skill = install_skill(project_root)
    except Exception as exc:
        return 1, fail("skill-install", str(exc), project_root=json_safe_path(project_root))

    try:
        plugin = build_plugin()
    except Exception as exc:
        return 1, fail("plugin-build", str(exc), project_root=json_safe_path(project_root), skill=skill)

    try:
        overlay = write_overlay(project_root)
    except Exception as exc:
        return 1, fail(
            "overlay-write",
            str(exc),
            project_root=json_safe_path(project_root),
            skill=skill,
            plugin=plugin,
        )

    argv = ["dsh", "web", "--patch", overlay["path"]]
    return 0, {
        "ok": True,
        "project_root": json_safe_path(project_root),
        "skill": skill,
        "plugin": plugin,
        "overlay": overlay,
        "activation": {
            "active_in_current_process": False,
            "restart_required": True,
            "argv": argv,
        },
        "source_checkout": {
            "path": json_safe_path(ROOT),
            "runtime_dependency": True,
            "note": "The generated overlay references this checkout's integrations/dsh/dist/index.js; do not delete it after bootstrap.",
        },
    }


def main() -> int:
    args = parse_args()
    exit_code, payload = bootstrap(Path(args.project_root))
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    elif payload.get("ok"):
        argv = payload["activation"]["argv"]
        print("Student OS DSH bootstrap complete.")
        print("Restart DSH with:")
        print(" ".join(argv))
    else:
        print(f"Student OS DSH bootstrap failed at {payload.get('stage')}: {payload.get('error')}", file=sys.stderr)
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
