import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
INSTALLER = ROOT / "scripts" / "install_student_os.py"
PLUGIN_ROOT = ROOT / "integrations" / "dsh"
PLUGIN_ENTRY = PLUGIN_ROOT / "dist" / "index.js"
OVERLAY_RELATIVE = Path(".dsh") / "student-os.cordis.yml"
SKILL_RELATIVE = Path(".dsh") / "skills" / "student-os"
MANIFEST_NAME = ".student-os-install.json"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Bootstrap Student OS project-scope support for DeepSeek Harness.")
    parser.add_argument(
        "--project-root",
        required=True,
        help="Target learning vault / current DSH workspace. This is not the college-student-workflow checkout.",
    )
    parser.add_argument("--json", action="store_true", help="Print machine-readable output.")
    parser.add_argument(
        "--force-overlay",
        action="store_true",
        help="Overwrite an existing different project overlay after writing a backup.",
    )
    return parser.parse_args()


def json_safe_path(path: Path) -> str:
    return str(path.resolve())


def yaml_single_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def overlay_text(plugin_entry: Path) -> str:
    # Windows 下 Node ESM loader 要求 file:// URL（普通绝对路径会被当成 scheme 为
    # "d:" 的 URL 而报 ERR_UNSUPPORTED_ESM_URL_SCHEME）；as_uri() 跨平台生成
    # file:///D:/...（Windows）或 file:///...（POSIX），二者都是合法 ESM 入口。
    plugin_url = plugin_entry.resolve().as_uri()
    return (
        "# Generated by scripts/bootstrap_dsh.py. Keep this project-local.\n"
        "- insert:\n"
        "    - id: student-os-native\n"
        f"      name: {yaml_single_quote(plugin_url)}\n"
    )


def run_checked(argv: list[str], *, cwd: Path, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        argv,
        cwd=cwd,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
        env={
            **os.environ,
            "PYTHONIOENCODING": "utf-8",
            "PYTHONDONTWRITEBYTECODE": "1",
            **(env or {}),
        },
    )


def fail(stage: str, error: str, **extra: Any) -> dict[str, Any]:
    return {"ok": False, "stage": stage, "error": error, **extra}


def path_is_relative_to(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


def git_status(project_root: Path) -> dict[str, Any]:
    git_exe = shutil.which("git.exe") or shutil.which("git")
    if git_exe is None:
        return {"available": False, "entries": [], "error": "git executable was not found on PATH"}
    result = subprocess.run(
        [git_exe, "-C", str(project_root), "status", "--porcelain=v1", "--untracked-files=all"],
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )
    if result.returncode != 0:
        message = (result.stderr or result.stdout).strip()
        return {"available": False, "entries": [], "error": message}
    return {"available": True, "entries": sorted(result.stdout.splitlines())}


def git_delta(before: dict[str, Any], after: dict[str, Any]) -> dict[str, Any]:
    if not before.get("available") or not after.get("available"):
        return {"before": before, "after": after, "added": [], "removed": []}
    before_entries = set(before.get("entries", []))
    after_entries = set(after.get("entries", []))
    return {
        "before": before,
        "after": after,
        "added": sorted(after_entries - before_entries),
        "removed": sorted(before_entries - after_entries),
    }


def file_digest(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def dsh_file_snapshot(project_root: Path) -> dict[str, str]:
    dsh_root = project_root / ".dsh"
    if not dsh_root.exists():
        return {}
    snapshot: dict[str, str] = {}
    for path in sorted(dsh_root.rglob("*")):
        if not path.is_file():
            continue
        resolved = path.resolve()
        if not path_is_relative_to(resolved, project_root):
            continue
        snapshot[path.relative_to(project_root).as_posix()] = file_digest(path)
    return snapshot


def dsh_file_delta(before: dict[str, str], after: dict[str, str]) -> dict[str, list[str]]:
    before_keys = set(before)
    after_keys = set(after)
    common = before_keys & after_keys
    return {
        "added": sorted(after_keys - before_keys),
        "removed": sorted(before_keys - after_keys),
        "modified": sorted(path for path in common if before[path] != after[path]),
    }


def operation_delta(
    before_git: dict[str, Any],
    before_files: dict[str, str],
    project_root: Path,
) -> dict[str, Any]:
    after_git = git_status(project_root)
    delta = git_delta(before_git, after_git)
    delta["dsh_files"] = dsh_file_delta(before_files, dsh_file_snapshot(project_root))
    return delta


def validate_project_paths(project_root: Path) -> None:
    reject_existing_symlink_components(project_root, SKILL_RELATIVE)
    reject_existing_symlink_components(project_root, OVERLAY_RELATIVE)
    checks = [
        project_root / SKILL_RELATIVE,
        project_root / OVERLAY_RELATIVE,
        (project_root / OVERLAY_RELATIVE).parent,
    ]
    for path in checks:
        resolved = path.resolve()
        if not path_is_relative_to(resolved, project_root):
            raise RuntimeError(f"Refusing to write outside project root via resolved path: {path} -> {resolved}")


def reject_existing_symlink_components(project_root: Path, relative: Path) -> None:
    current = project_root
    for part in relative.parts:
        current = current / part
        if current.is_symlink():
            raise RuntimeError(f"Refusing to write through symlink path component: {current}")


def existing_skill(project_root: Path) -> dict[str, Any] | None:
    destination = (project_root / SKILL_RELATIVE).resolve()
    manifest_path = destination / MANIFEST_NAME
    skill_path = destination / "SKILL.md"
    if not destination.exists():
        return None
    if not manifest_path.exists() or not skill_path.exists():
        return None
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if manifest.get("agent") != "dsh" or manifest.get("scope") != "project":
        return None
    if Path(str(manifest.get("target_path", ""))).resolve() != destination:
        return None
    return {
        "installed": True,
        "path": json_safe_path(destination),
        "status": "unchanged",
        "method": str(manifest.get("install_method", "")),
        "manifest": json_safe_path(manifest_path),
    }


def install_skill(project_root: Path) -> dict[str, Any]:
    current = existing_skill(project_root)
    if current is not None:
        return current

    try:
        result = run_checked(
            [
                sys.executable,
                "-B",
                str(INSTALLER),
                "--agent",
                "dsh",
                "--scope",
                "project",
                "--project-root",
                str(project_root),
                "--json",
            ],
            cwd=ROOT,
        )
    except subprocess.CalledProcessError as exc:
        message = (exc.stderr or exc.stdout or str(exc)).strip()
        raise RuntimeError(message) from exc

    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"Installer did not return JSON: {exc}") from exc

    installs = payload.get("results")
    if not isinstance(installs, list) or len(installs) != 1:
        raise RuntimeError("Installer returned an unexpected result shape")
    install = installs[0]
    destination = Path(str(install.get("destination", project_root / SKILL_RELATIVE))).resolve()
    return {
        "installed": True,
        "path": json_safe_path(destination),
        "status": install.get("status", ""),
        "method": install.get("method", ""),
        "manifest": install.get("manifest", ""),
    }


def build_plugin() -> dict[str, Any]:
    if not (PLUGIN_ROOT / "package-lock.json").exists():
        raise RuntimeError("integrations/dsh/package-lock.json is required for npm ci")
    node_exe = shutil.which("node.exe") or shutil.which("node")
    npm_exe = shutil.which("npm.cmd") or shutil.which("npm")
    if node_exe is None:
        raise RuntimeError("Node.js executable was not found on PATH")
    if npm_exe is None:
        raise RuntimeError("npm executable was not found on PATH")

    try:
        run_checked([npm_exe, "ci", "--ignore-scripts", "--no-audit", "--no-fund"], cwd=PLUGIN_ROOT)
        run_checked([npm_exe, "run", "build"], cwd=PLUGIN_ROOT)
    except subprocess.CalledProcessError as exc:
        detail = (exc.stderr or exc.stdout or str(exc)).strip()
        raise RuntimeError(detail) from exc

    if not PLUGIN_ENTRY.exists():
        raise RuntimeError(f"Plugin build did not create {PLUGIN_ENTRY}")
    return {
        "built": True,
        "source": json_safe_path(PLUGIN_ROOT),
        "entry": json_safe_path(PLUGIN_ENTRY),
    }


def next_backup_path(path: Path) -> Path:
    backup = path.with_name(path.name + ".bak")
    if backup.is_symlink():
        raise RuntimeError(f"Refusing to use symlink backup path: {backup}")
    if not backup.exists():
        return backup
    index = 1
    while True:
        candidate = path.with_name(f"{path.name}.bak.{index}")
        if candidate.is_symlink():
            raise RuntimeError(f"Refusing to use symlink backup path: {candidate}")
        if not candidate.exists():
            return candidate
        index += 1


def copy_backup_exclusive(source: Path, backup: Path) -> None:
    flags = os.O_CREAT | os.O_EXCL | os.O_WRONLY
    fd = os.open(str(backup), flags)
    try:
        with source.open("rb") as source_handle, os.fdopen(fd, "wb") as backup_handle:
            fd = -1
            shutil.copyfileobj(source_handle, backup_handle)
        shutil.copystat(source, backup)
    finally:
        if fd != -1:
            os.close(fd)


def write_overlay(project_root: Path, *, force_overlay: bool) -> dict[str, Any]:
    reject_existing_symlink_components(project_root, OVERLAY_RELATIVE)
    overlay = (project_root / OVERLAY_RELATIVE).resolve()
    if not path_is_relative_to(overlay, project_root):
        raise RuntimeError(f"Refusing to write overlay outside project root: {overlay}")
    overlay.parent.mkdir(parents=True, exist_ok=True)
    desired = overlay_text(PLUGIN_ENTRY)
    backup_path: Path | None = None
    if overlay.exists():
        reject_existing_symlink_components(project_root, OVERLAY_RELATIVE)
        current = overlay.read_text(encoding="utf-8")
        if current == desired:
            return {"written": False, "path": json_safe_path(overlay), "status": "unchanged"}
        if not force_overlay:
            raise RuntimeError(f"Overlay already exists with different content: {overlay}. Re-run with --force-overlay to replace it.")
        while True:
            backup_path = next_backup_path(overlay)
            try:
                copy_backup_exclusive(overlay, backup_path)
                break
            except FileExistsError:
                reject_existing_symlink_components(project_root, OVERLAY_RELATIVE)
                current = overlay.read_text(encoding="utf-8")
                if current == desired:
                    return {"written": False, "path": json_safe_path(overlay), "status": "unchanged"}
                continue
    reject_existing_symlink_components(project_root, OVERLAY_RELATIVE)
    overlay.write_text(desired, encoding="utf-8")
    result = {"written": True, "path": json_safe_path(overlay), "status": "written"}
    if backup_path is not None:
        result["backup"] = json_safe_path(backup_path)
    return result


def bootstrap(project_root: Path, *, force_overlay: bool) -> tuple[int, dict[str, Any]]:
    project_root = project_root.resolve()
    root = ROOT.resolve()
    if project_root == root or path_is_relative_to(project_root, root):
        return 1, fail(
            "project-root",
            "Refusing to use the college-student-workflow checkout as the target DSH project root.",
            project_root=json_safe_path(project_root),
        )

    before_git = git_status(project_root)
    before_files = dsh_file_snapshot(project_root)
    try:
        project_root.mkdir(parents=True, exist_ok=True)
    except Exception as exc:
        return 1, fail("project-root", str(exc), project_root=json_safe_path(project_root))

    try:
        validate_project_paths(project_root)
    except Exception as exc:
        return 1, fail(
            "project-root",
            str(exc),
            project_root=json_safe_path(project_root),
            git=operation_delta(before_git, before_files, project_root),
        )

    try:
        skill = install_skill(project_root)
    except Exception as exc:
        return 1, fail(
            "skill-install",
            str(exc),
            project_root=json_safe_path(project_root),
            git=operation_delta(before_git, before_files, project_root),
        )

    try:
        plugin = build_plugin()
    except Exception as exc:
        return 1, fail(
            "plugin-build",
            str(exc),
            project_root=json_safe_path(project_root),
            skill=skill,
            git=operation_delta(before_git, before_files, project_root),
        )

    try:
        overlay = write_overlay(project_root, force_overlay=force_overlay)
    except Exception as exc:
        return 1, fail(
            "overlay-write",
            str(exc),
            project_root=json_safe_path(project_root),
            skill=skill,
            plugin=plugin,
            git=operation_delta(before_git, before_files, project_root),
        )

    argv = ["dsh", "web", "--patch", overlay["path"]]
    return 0, {
        "ok": True,
        "project_root": json_safe_path(project_root),
        "skill": skill,
        "plugin": plugin,
        "overlay": overlay,
        "git": operation_delta(before_git, before_files, project_root),
        "activation": {
            "active_in_current_process": False,
            "restart_required": True,
            "argv": argv,
        },
        "source_checkout": {
            "path": json_safe_path(ROOT),
            "runtime_dependency": True,
            "note": "The generated overlay references this checkout's integrations/dsh/dist/index.js; do not delete it after bootstrap.",
        },
    }


def main() -> int:
    args = parse_args()
    exit_code, payload = bootstrap(Path(args.project_root), force_overlay=args.force_overlay)
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    elif payload.get("ok"):
        argv = payload["activation"]["argv"]
        print("Student OS DSH bootstrap complete.")
        print("Restart DSH with:")
        print(" ".join(argv))
    else:
        print(f"Student OS DSH bootstrap failed at {payload.get('stage')}: {payload.get('error')}", file=sys.stderr)
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
